#!/usr/bin/env python3
"""
Merge matugen config.toml files.

Reads the base config and all *.toml files in conf.d/, merges their
[config] and [templates.*] sections, and writes the merged result.

Custom files override the base on template name conflict; insertion order
is preserved so matugen runs templates in the intended sequence.

Output conventions (consumed by switchwall.sh):
    stdout - machine-readable lines (e.g. "SKIPPED:/path:error")
    stderr - human-readable diagnostics (warnings, success, errors)

Usage:
    python3 merge_matugen_config.py [--base PATH] [--conf-d PATH] [--output PATH]
"""

import sys
import os
import argparse
from pathlib import Path

# tomllib is stdlib from Python 3.11+; fall back to tomli for older versions
try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        print("Error: requires Python 3.11+ or 'tomli' package (pip install tomli)", file=sys.stderr)
        sys.exit(1)


def parse_args() -> argparse.Namespace:
    """Configure and parse command-line arguments."""
    xdg_config = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    xdg_cache  = Path(os.environ.get("XDG_CACHE_HOME",  Path.home() / ".cache"))

    parser = argparse.ArgumentParser(description="Merge matugen config.toml files")
    parser.add_argument(
        "--base", type=Path,
        default=xdg_config / "matugen/config.toml",
        help="Path to the base config.toml",
    )
    parser.add_argument(
        "--conf-d", type=Path,
        default=xdg_config / "matugen/conf.d",
        help="Directory containing additional *.toml files to merge",
    )
    parser.add_argument(
        "--output", type=Path,
        default=xdg_cache / "quickshell/matugen/config.toml",
        help="Path to write the merged config.toml",
    )
    return parser.parse_args()


def load_toml(path: Path) -> dict:
    """Load a TOML file. Returns an empty dict if the file does not exist or fails to parse.
    On parse failure emits a machine-readable SKIPPED line on stdout for the caller to handle."""
    if not path.is_file():
        return {}
    try:
        with open(path, "rb") as f:
            return tomllib.load(f)
    except Exception as e:
        # Machine-readable format consumed by switchwall.sh
        print(f"SKIPPED:{path}:{e}")
        print(f"Warning: could not parse {path}: {e}", file=sys.stderr)
        return {}


def toml_value(value) -> str:
    """Serialize a Python value to a TOML-compatible string."""
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, str):
        # Prefer single-quoted literal strings to avoid escaping issues with paths
        if "'" not in value:
            return f"'{value}'"
        # Fall back to basic strings with minimal escaping
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return f"[{', '.join(toml_value(v) for v in value)}]"
    return repr(value)


def write_merged(data: dict, output: Path) -> None:
    """Write the merged data to a TOML file, preserving insertion order."""
    output.parent.mkdir(parents=True, exist_ok=True)

    lines = ["# Generated by merge_matugen_config.py", ""]

    # [config] section
    if data.get("config"):
        lines.append("[config]")
        for k, v in data["config"].items():
            lines.append(f"{k} = {toml_value(v)}")
        lines.append("")

    # [templates.*] sections — order is preserved intentionally
    for name, values in data.get("templates", {}).items():
        lines.append(f"[templates.{name}]")
        for k, v in values.items():
            lines.append(f"{k} = {toml_value(v)}")
        lines.append("")

    output.write_text("\n".join(lines))


def main() -> int:
    args = parse_args()

    # Start with the base config
    merged = load_toml(args.base)

    # Merge all *.toml files from conf-d in alphabetical order.
    # Custom files override the base on name conflict.
    if args.conf_d.is_dir():
        for toml_file in sorted(args.conf_d.glob("*.toml")):
            # Skip if the file somehow resolves to the base config
            if toml_file.resolve() == args.base.resolve():
                continue

            data = load_toml(toml_file)

            if "config" in data:
                merged.setdefault("config", {}).update(data["config"])

            if "templates" in data:
                merged.setdefault("templates", {}).update(data["templates"])

    if not merged:
        print(f"Error: no config found (base: {args.base}, conf-d: {args.conf_d})", file=sys.stderr)
        return 1

    write_merged(merged, args.output)
    print(f"Merged config written to: {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())